<?php

namespace ContainerNnst48v;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescriptionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PrescriptionRepository' shared autowired service.
     *
     * @return \App\Repository\PrescriptionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PrescriptionRepository'] = new \App\Repository\PrescriptionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
