<?php

namespace ContainerWkTyzzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_Security_Firewall_Authenticator_ApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.firewall.authenticator.api' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['debug.security.authenticator.jwt.api'] ?? $container->load('getDebug_Security_Authenticator_Jwt_ApiService'));

        if (isset($container->privates['debug.security.firewall.authenticator.api'])) {
            return $container->privates['debug.security.firewall.authenticator.api'];
        }

        $instance = new \Symfony\Component\Security\Http\Authenticator\Debug\TraceableAuthenticatorManagerListener(new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['debug.security.event_dispatcher.api'] ?? $container->load('getDebug_Security_EventDispatcher_ApiService')), 'api', ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')), true, \Symfony\Component\Security\Http\Authentication\ExposeSecurityLevel::None, [])));

        if (isset($container->privates['debug.security.firewall.authenticator.api'])) {
            return $container->privates['debug.security.firewall.authenticator.api'];
        }

        return $container->privates['debug.security.firewall.authenticator.api'] = $instance;
    }
}
