<?php

namespace ContainerWkTyzzx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctorRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\DoctorRepository' shared autowired service.
     *
     * @return \App\Repository\DoctorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DoctorRepository'] = new \App\Repository\DoctorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
