<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNnst48v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNnst48v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNnst48v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNnst48v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNnst48v\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nnst48v',
    'container.build_id' => 'b9e3236e',
    'container.build_time' => 1773137865,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNnst48v');
